### ISSUE TITLE
Setup NEXT.js and Tailwind (Individual)

### ISSUE THREAD

**Issue by M6rk** [chpsmstr/eduQuest#22]
Each team member must setup the stack (Tailwind CSS and NEXT.js) on their machine(s). After completing this step then the team can begin programming. Comment 👍 to signify you have setup the stack on your machine(s).

**Comment by ankkprak** [comment]
👍

**Comment by M6rk** [comment]
👍

**Comment by nolannish** [comment]
👍

**Comment by Acr0batOG** [comment]
👍

**Comment by M6rk** [comment]
👍

**Comment by Daniel-Penner** [comment]
👍

**Comment by M6rk** [comment]
All team members have setup the stack on their machine(s).
