### ISSUE TITLE
Figma Wireflow - Phase #1

### ISSUE THREAD

**Issue by M6rk** [chpsmstr/eduQuest#23]
Create a page-by-page design of the application in Figma. This design will outline core features and design elements that will be implemented in the frontend portion of EduQuest. Prototyping should be used solely to demonstrate how pages/interactions are linked together. Phase #1 will involve the creation of the homepage, login, and registration pages on both desktop and mobile views.

**Comment by ankkprak** [comment]
Make sure the wireframes for figma are mobile first, since that is more often than not the limiting factor.

**Comment by M6rk** [comment]
Phase #1 has been completed. The homepage, login, and registration pages have been laid out and will be able to be coded into the frontend.
