### ISSUE TITLE
Describe Design Patterns

### ISSUE THREAD

**Issue by Daniel-Penner** [chpsmstr/eduQuest#29]
Describe at least two design patterns to implement for the project. Clearly explain why we have chosen those design patterns and how they will be implemented.

**Comment by M6rk** [comment]
Design patterns have been selected and described. Before closing this issue please discuss these choices with the rest of the team.

**Comment by M6rk** [comment]
Three design patterns have been explained within the document. The choices have been discussed during the follow-up meeting and have been approved. Note: Before submitting the M3 doc make sure to review one last time as a precautionary measure.
