### ISSUE TITLE
Text color across eduQuest

### ISSUE THREAD

**Issue by Acr0batOG** [chpsmstr/eduQuest#53]
Text color appears white on some machines and black on others. Not sure what is causing this.

**Comment by ankkprak** [comment]
Text color isn't manually specified in tailwind. As such, it defaults to white on dark mode machines and black on light mode machines.

**Comment by ankkprak** [comment]
This is an easy fix, just have the text color specified. Consult tailwind docs to get appropriate class name.

**Comment by M6rk** [comment]
Issue has been solved and discussed with the team.
